### ISSUE TITLE
Trying to contact you about one of your broken chocolatey pkg

### ISSUE THREAD

**Issue by xse** [echizenryoma/Chocolatey-Package#1]
Hi there !
I'm trying to contact you here even if this repository isn't directly related to the broken package because there doesn't seems to be any mail or other way to contact you, since i saw that you're active on this repo i'll try this way.

So, your package for [x64dbg on the public chocolatey depot](https://chocolatey.org/packages/x64dbg.portable) seems broken, I'm getting a checksum error when trying to install it.

![](https://i.imgur.com/5b4BbDE.png)

On another note, it might be a good idea to update it too since it hasn't been done since the 4/4/2017 and [plenty of new versions](https://github.com/x64dbg/x64dbg/releases) have been released since.

Anyway i hope you see this message, have a good day !

**Comment by echizenryoma** [comment]
Thank you for your noticing. Then I will update this package by using github repo.
