### ISSUE TITLE
Outdated package on Chocolatey.org

### ISSUE THREAD

**Issue by boubou** [echizenryoma/Chocolatey-Package#11]
Hi,
 
I saw that your chocolatey package, https://chocolatey.org/packages/windows-repair-toolbox, is outdated and you didnt update it since many many weeks.
 
Do you want to keep that package ?
 
I can maintain that package if you want.
Please add me as a maintainer on the package if you want.
My username is boubou.
 
Thanks for keep me updated.
 
Sébastien

**Comment by echizenryoma** [comment]
Chocolatey.org tell me: Validation Testing Failed.
BUT I can use it normally by local repo.

**Comment by boubou** [comment]
Hi again,
Thanks you for your answer.
On the Windows-Repair-Toolbox website, it looks like there are many many news versions.
Program version:  3.0.2.1 (24.08.2019)
Definitions version: 1.5.0.9 (11.11.2019)

You can choose 2 options: ;)
1. Update it yourself asap plz.
2. Add me as a maintainer and I will do it.

Thanks and please let me know.

**Comment by echizenryoma** [comment]
I have added "boubou" as a maintainer.
