### ISSUE TITLE
x64dbg - Failed to save settings

### ISSUE THREAD

**Issue by 0xE9DEADBEEF** [echizenryoma/Chocolatey-Package#17]
![image](https://user-images.githubusercontent.com/47276302/169769250-43aeae97-a6d3-4289-841a-ec8b96e11e58.png)

x64dbg tries to save its configuration under the path `C:\ProgramData\chocolatey\lib\x64dbg.portable\tools\release\`. However the user does not have write permissions. I managed it by changing the folder rights manually. Unfortunately at every `choco update`, the rights return as before ;-(

**Comment by echizenryoma** [comment]
move to opt

**Comment by echizenryoma** [comment]
Move to scoop and stop update it.
