### ISSUE TITLE
Bat To Exe converter

### ISSUE THREAD

**Issue by aetonsi** [echizenryoma/Chocolatey-Package#18]
Hi,
are/were you the maintainer of the `battoexeconverter` package? The chocolatey listing points to a missing subfolder in this repo, so i don't know if i'm in the right place..
If i am, could you please restore and/or update the package? The developer (FK) released one final version, v3.2.0, you can easily check online (and download it from anywhere).
The [original github project is dead](https://github.com/99fk), but in the sidebar there's an [ipfs link that takes to a page with the download link for that exact version](https://ipfs.io/ipfs/QmPFVJQZ54xuCQ54B5DdfyejSBKTSLbHSKtF9YpunsRpWh).

The new location for the author's software, including the one in question, is [this zeronet space](http://127.0.0.1:43110/17SWVnHoujG92yYGSZvCzPgZEpGVfRF8wi) (requires [Zeronet](https://zeronet.io/docs/using_zeronet/installing/)).

Thank you for your attention

**Comment by echizenryoma** [comment]
Thanks

**Comment by aetonsi** [comment]
Just to be sure, you are _still_ maintaining it? Because i see you removed its folder from this repo a few years ago... just asking to know if the choco version will be updated to the new one i linked, or not.

have a nice day

**Comment by echizenryoma** [comment]
But it didn't open source code.

**Comment by aetonsi** [comment]
You mean the script couldn't download it?

**Comment by echizenryoma** [comment]
the script can download it.

**Comment by aetonsi** [comment]
Oh ok. So it works? I don't understand what you meant by this:


> But it didn't open source code.
