### ISSUE TITLE
VSCode.portable - data folder should not be deleted when updating

### ISSUE THREAD

**Issue by berknam** [echizenryoma/Chocolatey-Package#2]
Like the title says the "data" folder from vscode shouldn't be deleted. It contains all the user settings and installed extensions. We need to backup the folder before updating and then paste it again.

If you change this line in 'ChocolateyInstall.ps1' file:

https://github.com/echizenryoma/Chocolatey-Package/blob/504d8c39608f80276898893413a3a93a1b8cac1e/vscode.portable/tools/ChocolateyInstall.ps1#L12

to

`Get-ChildItem -Path $InstallationPath -Exclude data | Remove-Item -Recurse -Force -ErrorAction Ignore`

Should fix it.

**Comment by echizenryoma** [comment]
Thanks. I have been merged.
