### ISSUE TITLE
x64dbg.portable causes HTTP 404

### ISSUE THREAD

**Issue by Phaeilo** [echizenryoma/Chocolatey-Package#5]
The package `x64dbg.portable` references the following URL:

`https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2018-12-30_23-09.zip`

Requesting this file causes a HTTP 404 and causes package install to fail. The package should be updated to point to the newest release ZIP.

**Comment by echizenryoma** [comment]
Ok. I have enabled url check and updated this package.
