### ISSUE TITLE
(jdk.portable) broken for powershell v2

### ISSUE THREAD

**Issue by teknowledgist** [echizenryoma/Chocolatey-Package#6]
Hi.  Thanks for maintaining this package.

I am running into an error when trying to install on a system with PowerShell v2 due to the use of the `-file` switch on `Get-ChildItem`.  Could you change the three lines to remove the `-file` and pipe the results of the `gci` to `Where-Object { !$_.PSIsContainer }`?  That shouldn't hurt the functionality for systems with newer versions of PoSh, but will help those on older versions.

Thanks!

**Comment by echizenryoma** [comment]
Could you tell me your jdk.portable version? Do you mean jdk8.portable?

**Comment by teknowledgist** [comment]
I had the problem trying to install the latest jdk8.portable package v8.0.202, but after a quick look at the chocolateyinstall.ps1 for the jdk.portable package, I can see the same issue.

**Comment by echizenryoma** [comment]
Your OS is Windows 7?

**Comment by teknowledgist** [comment]
Some of my machines are Win7, yes, but that's beside the point.   

Chocolatey itself is entirely PoSh v2 compatible as are the (vast?) majority of other packages.  I am pretty certain that when I started with Chocolatey, there was a recommendation to make packages for v2, but I can't find that stated anywhere at the moment.  

If you can easily make the package work for the lowest common denominator (PowerShell v2), then what is the harm?

**Comment by echizenryoma** [comment]
If I just modify this package to support PowerShell v2, it can be easy. But if I modify wholes packages, it is very heavy workload for me. You may use the PowerShell Core 6.0 in your machine. Thank you for your understanding.

**Comment by teknowledgist** [comment]
I'm not quite clear on where the heavy workload comes in.  I took quick scan through your other packages and I don't see anything else that would need to be changed.  Also, it wouldn't make sense to change older versions of this package.  I just thought it would be pretty easy to make this (and future) versions of the package compatible for the most users.

Of course, it is your package.  You can do (or not do) what you want.  Thanks for considering it.

**Comment by echizenryoma** [comment]
I need to check all PowerShell scripts under PowerShell v2. Now, I find many parameters of command is not supported by PowerShell v2, for example,  Remove-Item -ErrorAction does not support Ignore action; [IO.Path]::Combine does not support multiple parameters. I must takes much time to do this. 
Thank you for your understanding.

**Comment by echizenryoma** [comment]
jdk8.portable can't download Java 8 without an Oracle account. Please use openjdk8.adopt to replace jdk8.portable. Thanks.
